steps:
  # Install dependencies
  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['ci']

  # Run linting (optional, remove if no lint script)
  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['run', 'lint']

  # Build the application
  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/a4ai-frontend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/a4ai-frontend:latest',
      '.'
    ]

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/a4ai-frontend:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'a4ai-frontend',
      '--image', 'gcr.io/$PROJECT_ID/a4ai-frontend:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '512Mi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '100',
      '--port', '8080'
    ]

timeout: '1200s'

# Optional: Build substitutions for environment variables
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'a4ai-frontend'
